### PR TITLE
Added request retry mechanism to HttpSender

### PR DESCRIPTION
**Pull request by NSocec-Mindsmiths**
In its current implementation, the HttpSender class will not try to repeat a POST request if it fails. This can lead to a situation where events get dropped (they get removed from the queue, but they don't arrive at the server).

To resolve this, a retrying mechanism was implemented. The mechanism can be configured by setting the maximum number of retries before giving up and by setting the time interval between retries.

### CODE REVIEW

**Comment by hazzadous** [comment]
Great! Thanks @NSocec-Mindsmiths I'll review this tomorrow time permitting.

**Comment by NSocec-Mindsmiths** [comment]
Great, thank you for your time.

**Comment by hazzadous** [comment]
I have merge in #33 and we'll get a release in soon

**Comment by pauldambra** [comment]
@NSocec-Mindsmiths 👋 

We've released posthog-java 1.1.0 

Thank you so much for the contribution!

**Pull request closed without merging**
